mysql_root_password: 'root'
mysql_bind_address: '127.0.0.1'
mysql_databases:
  - name: example_db
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: example_user
    host: "%"
    password: 'q'
    priv: "example_db.*:ALL"
