---
- name: Install MySQL
  hosts: localhost
  tasks:
      - name: install mysql
        apt: name=mariadb-server update_cache=yes

      - name: add mysql user
        user: name=mysql home=/var/lib/mysql

      - name: restart mysql service
        service: name=mysql state=restarted
